language: ruby
rvm:
- 2.3.4
cache: bundler
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - "./cc-test-reporter before-build"
after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
deploy:
  provider: rubygems
  api_key:
    secure: fqrdBHXIfC25QtO6l3GDg81OxY6ImeqjEDEsHN0Y2FgQkfkTWZJOuRU6r/voDQIKGGWV0iZM8YTg0aEV/odpCGtBRz7fFBUUOK0q0xWQE7oZQNTj7d3JQrHrbsyaMnl4SqqV8RKOkV2J2nQ4/r6864Q549QNNiN0QD1SyfqbLL1ZW09kFsf1ze/m+s2eN1+sLPDpt/d8Yp4B/eaLo0qJC0aXufKNVHL92Zv4wksqZ6rTFHCJ60/1h51IXC4SwwTh81Hy8Xp0ZRfELaTURxX1Pt6GIIpz40jtMX20Tre26QAx6c75nZ0Y9xLZFacSVDjVuoNQx32ZcNOgiFqEShoucThhTWOo1XWwPfrp/jeFZ0KYC9pDv417GnaT0RpSBUPkWXZl6Lr92V0hgtMn2O3RCHxkVKWXuc4HNrgt8joCbuDcfRZPtFEnJKsGsGyclxZ3rKjr3JwT18HyX1uBsR/daXOZHQcyJIhyMG6PFjFbeYTTwt7rJrhYDWdbs/R9tm6iIRHPPqv1Lug9rvpFyZQQABi00txJZPUK+SuAHKmlxsRc7isOoJjDmuc4KVLyH7cT6u1rZbU7Oy+C+YtJJ2dC3fovsqnXWtAqgLY8JkODTnfUF7mCWi+4lU1T99ik9ItOCd7I/OrVEsqlH7GhHM3zAmm+1ILANYtfAswTlvD2zvc=
  gem: validation_profiler
  on:
    tags: true
    condition: "$TRAVIS_RUBY_VERSION == 2.3.4"
env:
  global:
    secure: KA1qUbi73Z6PZeSJqvuHb0/QETH/HlAVzStt0qkIBoZ/Oug5cRutL8mLGyrVPadYdupvAAVNupEYWHm0oVZVURPrvfb6l3QtqfQEhjBeoPw5wjF0wLhGt1E2yjePYLp0Of4K+HIPuj19YnR4K5V7+ZixF/2VBDhdoLgerCntaGgCqUKt95ig6+4tbEksErjWWVAmtlyu2OPxileHi8VoFhaz2WNtH8uiCLjL0JGDrHPTFyBVpCbSDFIDQaqWIqXvplmBHtDkOjVX4lsi6bC39wMOqNKis+x0xn1MM6QTcOycyRYIpNXSKsIdIInSqG0EDKK1bw1Vy4rcX5BnfctKvdqTf6hJOY6LgUexLidAFfdFMvfPQ3/lYVoF8DStNVRgApuChTko0QU8yIgOHN6xD7Bk8jA497roxHgwKmjW6UmPb/KhvZtoDkNcFy5QeaCtDP+/JDuzo9UnLF3nlCBBEz/jilYwufO6VlQkI87IlFk18Ab9G5bWpCuIZTdtdLCPYZAHwB5upOXNXC8S86QSB9lrbZVfac+k50CyBe9jBPBNuu6CjqZ68j0X5/vZKc/0UWS8SH+2Yioc+gUqYB70I9b/Bez9JrPc5C2/ycmjL/C7fmyMdgeOho07YKfw4wj0xTG42sSsHYFrhrcFPvXLesH8lLbeqOfs4dP2HZMWKxo=
