language: ruby
rvm:
- 2.3.0
- 2.3.1

cache: bundler

deploy:
  provider: rubygems
  api_key:
    secure: "fqrdBHXIfC25QtO6l3GDg81OxY6ImeqjEDEsHN0Y2FgQkfkTWZJOuRU6r/voDQIKGGWV0iZM8YTg0aEV/odpCGtBRz7fFBUUOK0q0xWQE7oZQNTj7d3JQrHrbsyaMnl4SqqV8RKOkV2J2nQ4/r6864Q549QNNiN0QD1SyfqbLL1ZW09kFsf1ze/m+s2eN1+sLPDpt/d8Yp4B/eaLo0qJC0aXufKNVHL92Zv4wksqZ6rTFHCJ60/1h51IXC4SwwTh81Hy8Xp0ZRfELaTURxX1Pt6GIIpz40jtMX20Tre26QAx6c75nZ0Y9xLZFacSVDjVuoNQx32ZcNOgiFqEShoucThhTWOo1XWwPfrp/jeFZ0KYC9pDv417GnaT0RpSBUPkWXZl6Lr92V0hgtMn2O3RCHxkVKWXuc4HNrgt8joCbuDcfRZPtFEnJKsGsGyclxZ3rKjr3JwT18HyX1uBsR/daXOZHQcyJIhyMG6PFjFbeYTTwt7rJrhYDWdbs/R9tm6iIRHPPqv1Lug9rvpFyZQQABi00txJZPUK+SuAHKmlxsRc7isOoJjDmuc4KVLyH7cT6u1rZbU7Oy+C+YtJJ2dC3fovsqnXWtAqgLY8JkODTnfUF7mCWi+4lU1T99ik9ItOCd7I/OrVEsqlH7GhHM3zAmm+1ILANYtfAswTlvD2zvc="
  gem: validation_profiler
  on:
    tags: true

